apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels: 
    app: my-service
spec:
  selector:
    app: my-service
  ports:
  - name: http
    port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-service
  template:
    metadata:
      labels:
        app: my-service
        version: v1
    spec:
      containers:
      - name: my-service
        image: my-company.azurecr.io/my-service:#{Build.BuildId}#
        ports:
        - containerPort: 8000 
        env:
        - name: PORT
          value: "8000"
